### ISSUE TITLE
Should work together

### ISSUE THREAD

**Issue by niicojs** [TheTravelingTrainer/NecroWebGui#1]
I'm working on this: https://github.com/nicoschmitt/necrobotvisualizer.
It seems I'm in advance on the gui side but you've made last night so change on the bot side I  wanted to make also.
We should work together, I'm niico on discord.

**Comment by TheTravelingTrainer** [comment]
I'll catch you up on Discord once it's working again

I did see you GUI, but wanted to do something that didn't require node. 

Did you add the transfer task handler btw?

IF so could you do it like all your other ones? In the switch statement? Just the handlers use a callback system and I see you're broadcasting it to all which will cause issues.

The transfer event will already be fired to all on the normal channel anyways I think, if not they should. These methods are purely for the callback methods please.

thank you!!

**Comment by niicojs** [comment]
I did the transfer task indeed.
In that case it need to be bradcast because it's not a respond (like list) but a consequence that all client should have.

But you are 100% correct that all list events should not be broadcasted.

**Comment by TheTravelingTrainer** [comment]
Yeah, so it should ONLY respond to the caller that the task was completed. :) Hence the usage of request IDs.. So if a GUI was waiting for that task to happen, then its going to get confused as it doesn't come back via the same channel.

Does a transfer event not already send the event though? so do you not get the same info twice?

Also you shouldn't be putting all that logic into a handler, it should be a normal task thats called by the handler.

**Comment by niicojs** [comment]
let's continue on discord

**Comment by TheTravelingTrainer** [comment]
Cant workout how to send you a message lol... Says we're not in any of the same servers?

**Comment by niicojs** [comment]
https://discord.gg/VXKxNFr
